Update snyk-infrastructure.yml

diff --git a/.github/workflows/snyk-infrastructure.yml b/.github/workflows/snyk-infrastructure.yml
--- a/.github/workflows/snyk-infrastructure.yml
+++ b/.github/workflows/snyk-infrastructure.yml
@@ -20,10 +20,13 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
+      
       - name: Installing dependencies
         run: npm install
+        
       - name: Synk CLI setup
         uses: snyk/actions/setup@master
+        
       - name: Running Synk
         shell: bash
         continue-on-error: true
@@ -32,11 +35,15 @@ jobs:
         run: | 
               --sarif-file-output=snyk.sarif 
    
-      - name: Check if SARIF was created (Debugging)
-        run: ls -l snyk.sarif || echo "File not found"  
-        
+      - name: Debug of sarif file
+        run: | 
+            if [ -f "snyk.sarif" ]; then
+              echo "snyk.sarif exists."
+            else
+              echo "snyk.sarif NOT FOUND. Snyk might have failed to detect your project."
+              exit 1
+            fi        
       - name: Upload result to GitHub Code Scanning
-        if: always()
         uses: github/codeql-action/upload-sarif@v3
         with:
           sarif_file: snyk.sarif
